<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LatituteE7340" failures="1" tests="5" name="testEndPoints.AdequateEndpointTests" time="6.337" errors="0" timestamp="2023-04-30T23:56:16 IST" skipped="0">
  <testcase classname="testEndPoints.AdequateEndpointTests" name="TestUserRegister" time="4.775"/>
  <system-out/>
  <testcase classname="testEndPoints.AdequateEndpointTests" name="TestValidUserLogin" time="0.404">
    <failure message="expected [success] but found [invalid username or password]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [success] but found [invalid username or password]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at testEndPoints.AdequateEndpointTests.TestValidUserLogin(AdequateEndpointTests.java:88)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- TestValidUserLogin -->
  <system-out/>
  <testcase classname="testEndPoints.AdequateEndpointTests" name="TestCreateUser" time="0.433"/>
  <system-out/>
  <testcase classname="testEndPoints.AdequateEndpointTests" name="TestgetUser" time="0.416"/>
  <system-out/>
  <testcase classname="testEndPoints.AdequateEndpointTests" name="TestInValidUserLogin" time="0.309"/>
  <system-out/>
</testsuite> <!-- testEndPoints.AdequateEndpointTests -->
